### ISSUE TITLE
Push to origin wording change

### ISSUE THREAD

**Issue by element4l** [gitobsidiantutorial/obsidian-git-tut-windows#1]
I had to press something like "Publish to..." instead of "Push to origin" to get this to work. I realized because it said the shortcut was cntrl+P and it did the same thing, giving an alert at the top "pushing to origin." This should maybe be cleared up because it had me stumped for a little while.

**Comment by gitobsidiantutorial** [comment]
Is this in Obsidian Git or in Github Desktop?

**Comment by element4l** [comment]
GitHub Desktop

**Comment by gitobsidiantutorial** [comment]
All right, updating the readme file.

Thanks for your feedback!
