### ISSUE TITLE
Have to push to origin in Github Desktop

### ISSUE THREAD

**Issue by stupidanon** [gitobsidiantutorial/obsidian-git-tut-windows#2]
So the plugin works fine, but on my PC when I do git commit through the plugin, it brings up GitHub desktop and makes me push origin manually, kinda defying the point of the plugin. 

However, on my laptop, it automatically pushes and does not pop up with GitHub desktop. I don't know how its even possible, but I am getting two different results...

**Comment by foreveryone1** [comment]
Sounds like an issue with the path.

Could you go and follow the instructions [here](https://github.com/gitobsidiantutorial/obsidian-git-tut-windows/blob/main/Fixing%20PATH.md) and take a screenshot of the git path on your desktop?

**Comment by stupidanon** [comment]
> 
> 
> Sounds like an issue with the path.
> 
> Could you go and follow the instructions [here](https://github.com/gitobsidiantutorial/obsidian-git-tut-windows/blob/main/Fixing%20PATH.md) and take a screenshot of the git path on your desktop?

I can use git from any place in cmd window, it is in environment path. even in github desktop, i was able to do the authentication through command prompt as per the tutorial. I have a photo below of my vault and where the repo is stored. 
![image](https://user-images.githubusercontent.com/19488222/115231400-db196280-a158-11eb-9974-c2e645436d80.png)

**Comment by stupidanon** [comment]
I have discovered the problem and the solution. Windows credential manager had old credentials for the command given to create credentials. New credentials should be generated to fix this problem. 
The command `git config credential.helper store` is a more up to date version I think of what is in the README.md of this repo. 
So i deleted the windows credential from control panel for github, ran that command, then tried a git pull. It will ask for new credentials, input them, then obsidian git works as intended.

**Comment by gitobsidiantutorial** [comment]
I'd rather not have `git config credential.helper store` as the recommended credential saving command in the tutorial, as it has clear security drawbacks https://git-scm.com/docs/git-credential-store

What can be done instead is opening the credential manager in windows and removing invalid credentials.
